# Generated by Django 4.2 on 2023-04-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha_salida', models.DateField()),
                ('genero', models.CharField(choices=[('arcade', 'Arcade'), ('aventura', 'Aventura'), ('battle royale', 'Battle Royale'), ('carreras', 'Carreras'), ('cartas', 'Cartas'), ('city builder', 'City Builder'), ('deportes', 'Deportes'), ('estrategia', 'Estrategia'), ('hack and slash', 'Hack And Slash'), ('mmorpg', 'MMORPG'), ('moba', 'MOBA'), ('musica', 'Música'), ('pelea', 'Pelea'), ('plataformas', 'Plataformas'), ('rpg', 'RPG'), ('rpg por turnos', 'RPG Por Turnos'), ('rts', 'RTS'), ('roguelike', 'Roguelike'), ('sandbox', 'Sandbox'), ('shooter', 'Shooter'), ('sigilo', 'Sigilo'), ('simulador', 'Simulador'), ('terror', 'Terror'), ('tower defense', 'Tower Defense')], max_length=255)),
                ('empresa', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('valoracion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
            ],
        ),
    ]
